### ISSUE TITLE
Can't change fonts

### ISSUE THREAD

**Issue by vojtasrb** [Total-RP/Storyline#78]
Can't change any font in the GUI. The dropdown menu won't show up.

**Comment by Solanya** [comment]
Can you enable Lua errors with `/console scriptErrors 1` then reload and see if an error message shows up when you try to open the dropdown?
I don't seem to have that issue with the latest version.

![Untitled](https://user-images.githubusercontent.com/17127080/198854556-744d29ab-8ae7-4fd6-94eb-e492245d2fdd.png)

**Comment by vojtasrb** [comment]
> /console scriptErrors 1

Tried it but it doesn't show anything. What happens though when I click on the dropdown menu, everything lags for a second. So there is something happening there.

Maybe it's because I have like 50 fonts installed there and it's not able to load them? Although I didn't have any problems in other addons and they all show up.

**Comment by Solanya** [comment]
Doesn't seem like it, it doesn't behave particularly well with too many fonts but I'm not seeing any issue either.
Can you try with no other addon enabled and see if the issue still happens? If not, I'd have to know which addon is causing it to stop working.

![Untitled](https://user-images.githubusercontent.com/17127080/198877777-bcb44e0b-4731-4b9d-aa17-931473c82d29.png)

**Comment by vojtasrb** [comment]
> Doesn't seem like it, it doesn't behave particularly well with too many fonts but I'm not seeing any issue either. Can you try with no other addon enabled and see if the issue still happens? If not, I'd have to know which addon is causing it to stop working.
> 
> ![Untitled](https://user-images.githubusercontent.com/17127080/198877777-bcb44e0b-4731-4b9d-aa17-931473c82d29.png)

Okay, so I deactivated one of mine media addons, Ishtara media to be precise, and it worked. It seems like the dropdown menu doesn't work if there are so many options that it needs to have scrollbar. I think that was the problem.

I guess I'll have to clean and delete some of my stuff, so things like this won't happen again. 

Thanks for your help though!
