### ISSUE TITLE
tried to call the protected function 'MultiBarLeft:SetScaleBase()'.

### ISSUE THREAD

**Issue by uujfwmnp** [Total-RP/Storyline#81]
```
1x [ADDON_ACTION_BLOCKED] AddOn 'Storyline' tried to call the protected function 'MultiBarLeft:SetScaleBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetScaleBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:48: in function `SetScale'
[string "@FrameXML/EditModeManager.lua"]:584: in function `UpdateRightActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:556: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:676: in function `UpdateGridLayout'
[string "@FrameXML/ActionButton.lua"]:368: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:821: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>
```

I believe this started when I dropped into an LFG dungeon while the Storyline window was still on the screen.

**Comment by Solanya** [comment]
Edit Mode is messy currently and can easily lead to blocked actions later during the session, it's safer to /reload once you're done with modifications inside it to avoid those issues for now until Blizzard fixes it.

**Comment by uujfwmnp** [comment]
I was not in edit mode when this happened though.

**Comment by Solanya** [comment]
No, but you likely entered Edit Mode before in the session, leading to the issue happening later.

**Comment by uujfwmnp** [comment]
I can assure you, I did not enter edit mode. :)
I will keep an eye on this bug and reopen if it happens again, hopefully with more steps if it can be reproduced on a regular basis.
