### ISSUE TITLE
Issue with 3.3.5a Version

### ISSUE THREAD

**Issue by Th3AnG3L** [Total-RP/Storyline#82]
Hello first of all great addon,
But i have an issue regarding the addon for 3.3.5a version.

Is there a way where you start communication with NPC to give you quest to show you what reward you will receive like EXP,Items in advance, because now you can only accept the quest and when you return it it gives you the information reward.

Another thing to Accept only the quest by clicking the mark "Accept" or "Decline" arrow if you by mistake click on bottom text its automatically accepted.
Another thing is can you add a checkbox to display directly the whole conversation at one time for the quest? - So players can choose instant message read or story-tail mode.

or if you have already fix this and some version that will work for 3.3.5a please correct me with link to download.
Thank you.

**Comment by Solanya** [comment]
The addon is not supported on anything but the current Retail version, 10.0.2. Private server compatible forks may exist somewhere, but we can't help with those.

**Comment by Th3AnG3L** [comment]
okay i understand, is it going to be implement for that version too it would be really nice.

**Comment by Solanya** [comment]
I had stopped at the patch number and didn't read the rest.
First one could be considered, for the others it's unlikely I revisit those behaviours for now (although showing rewards earlier would allow access to accept/decline sooner too).

**Comment by Th3AnG3L** [comment]
yes it can be made to show rewards as information before accepting the quest so people know what this quest gives before accept it would be much better. Really love this mod beautiful.
