### ISSUE TITLE
FreezeAnimation error

### ISSUE THREAD

**Issue by Missratata** [Total-RP/Storyline#84]
Hi,
I just got this error, talking with Mangled Body in Southern Barrens.
Not sure what it is saying, so I hope I can get a little help :)

1x Storyline/PlayerModelMixin.lua:111: Usage: self:FreezeAnimation(anim, variation, frame)
[string "=[C]"]: in function `FreezeAnimation'
[string "@Storyline/PlayerModelMixin.lua"]:111: in function `DisplayDead'
[string "@Storyline/events.lua"]:495: in function <Storyline/events.lua:457>
[string "@Storyline/events.lua"]:529: in function <Storyline/events.lua:513>
[string "@Storyline/logic.lua"]:310: in function <Storyline/logic.lua:211>
[string "@Storyline/events.lua"]:765: in function <Storyline/events.lua:763>

Locals:
(*temporary) = Storyline_NPCFrameModelsYou {
 OnModelLoaded = <function> defined @Storyline/PlayerModelMixin.lua:58
 SetModelFacing = <function> defined @Storyline/PlayerModelMixin.lua:269
 RequiresManualAnimationTiming = <function> defined @Storyline/PlayerModelMixin.lua:103
 ResetIdleAnimationID = <function> defined @Storyline/PlayerModelMixin.lua:79
 SetModelUnit = <function> defined @Storyline/PlayerModelMixin.lua:91
 SetModelFeet = <function> defined @Storyline/PlayerModelMixin.lua:275
 SetModelHeight = <function> defined @Storyline/PlayerModelMixin.lua:263
 SetModelOffset = <function> defined @Storyline/PlayerModelMixin.lua:281
 modelLoadedPromise = <table> {
 }
 offset = 0.215000
 debug = Storyline_NPCFrameDebugSequenceYou {
 }
 OnAnimFinished = <function> defined @Storyline/PlayerModelMixin.lua:228
 AnimateScalingValuesIn = <function> defined @Storyline/PlayerModelMixin.lua:287
 PlayAnimation = <function> defined @Storyline/PlayerModelMixin.lua:142
 animationStartedTime = 151475.775000
 displayedModel = 1011653
 currentAnimation = 0
 isModelLoaded = false
 isPlayingAnimationSequence = false
 isPlayingIntersticeAnimation = true
 sequence = <table> {
 }
 facing = 0.750000
 SetCustomIdleAnimationID = <function> defined @Storyline/PlayerModelMixin.lua:73
 boundSetModelHeight = <function> defined @Storyline/lib/Ellyb/Tools/Functions.lua:21
 scale = 1.389000
 SetScalingValuesIn = <function> defined @Storyline/PlayerModelMixin.lua:294
 modelFeetTransitionator = <table> {
 }
 animationTries = 0
 animTab = <table> {
 }
 npc_id = "38878"
 isModelDisplayedOnLeft = false
 doNotAnimateScaling = false
 modelOffsetTransitionator = <table> {
 }
 0 = <userdata>
 DisplayDead = <function> defined @Storyline/PlayerModelMixin.lua:107
 GetValidSpeakingAnimation = <function> defined @Storyline/PlayerModelMixin.lua:117
 modelHeightTransitionator = <table> {
 }
 PlayIdleAnimation = <function> defined @Storyline/PlayerModelMixin.lua:149
 GetModelFileIDAsString = <function> defined @Storyline/PlayerModelMixin.lua:302
 OnLoad = <function> defined @Storyline/PlayerModelMixin.lua:42
 PlayAnimSequence = <function> defined @Storyline/PlayerModelMixin.lua:156
 boundSetModelFeet = <function> defined @Storyline/lib/Ellyb/Tools/Functions.lua:21
 ReplayAnimation = <function> defined @Storyline/PlayerModelMixin.lua:224
 feet = 0.400000
 SetAnimationWithFailSafe = <function> defined @Storyline/PlayerModelMixin.lua:208
 boundSetModelOffset = <function> defined @Storyline/lib/Ellyb/Tools/Functions.lua:21
 ModelLoaded = <function> defined @Storyline/logic.lua:130
 PlayNextAnimation = <function> defined @Storyline/PlayerModelMixin.lua:179
 idleAnimationID = 0
 scroll = Button {
 }
 ResetModel = <function> defined @Storyline/PlayerModelMixin.lua:83
 bindedOnAnimFinished = <function> defined @Storyline/lib/Ellyb/Tools/Functions.lua:21
}
(*temporary) = 1
(*temporary) = nil
(*temporary) = -1

**Comment by Solanya** [comment]
Will take a look as soon as I can, I have an idea of what might be the issue.
