### ISSUE TITLE
Compatibility with "RP Name in Quest Text" addon

### ISSUE THREAD

**Issue by NinerBull** [Total-RP/Storyline#86]
Hey there,
I'm the author of the [RP Name in Quest Text](https://github.com/NinerBull/tRP3_RPNameInQuests) addon, which is a module for TRP3 that swaps your OOC character name with your IC character name in quests etc, with info from your TRP3 profile.

Another user recently pointed out that it doesn't work correctly with Storyline. I've had a look, and it seems to be due to [events.lua](https://github.com/Total-RP/Storyline/blob/main/events.lua#L46), as it's creating local versions of the functions that get quest text, etc. [My addon modifies these functions](https://github.com/NinerBull/tRP3_RPNameInQuests/blob/main/tRP3_RPNameInQuests/tRP3_RPNameInQuests.lua#L664), but Storyline loads before TRP3's modules do.

[Commenting out lines 46 and 47 of events.lua](https://github.com/Total-RP/Storyline/blob/main/events.lua#L46) makes the module work.
Alternatively, adding `## OptionalDeps: totalRP3` to Storyline's TOC and wrapping the same lines above with `if (IsAddOnLoaded("totalRP3") == false) then` and `end` seems to do the job too. There's probably a nicer way to do this though, I'd guess!

Thank you for reading, I hope it's something you can take a look at when you have time.

**Comment by Solanya** [comment]
Hey,

Indeed aware of that one as of a few days ago, the same user came to our Discord asking about it, it'll be fixed for 10.2.5.

**Comment by NinerBull** [comment]
Nice one! Thank you very much for the super fast reply 🐮👍
